from typing import List
from abc import ABC

import httpx

from poke_challenge.schema import PokemonTypes, PokemonTypeCounter


class APIHandlerABC(ABC):
    async def get_single_pokemon_data(
        client: httpx.AsyncClient, name: str
    ): ...

    def get_data_from_api(self) -> List[PokemonTypes]: ...


class JsonFileHandlerABC(ABC):
    def __init__(self, ): ...
    def pydantic_to_json(self, result: dict): ...
    def save_to_file(self, data: dict): ...


class DatabaseHandlerABC(ABC):
    def __init__(self): ...
    async def query_counter(self) -> List[PokemonTypeCounter]: ...
    async def start_database(self) -> None: ...
    async def close(self) -> None: ...
    async def store_result(self, result: List[PokemonTypes]) -> None: ...
    async def all_pokemons(self) -> List[PokemonTypes.dict]: ...
    async def tortoise_up(self) -> None: ...


class ControllerABC(ABC):
    database_handler: DatabaseHandlerABC
    josn_handler: JsonFileHandlerABC
    api_handler: APIHandlerABC

    async def store_all_results(self, result: List[PokemonTypes]) -> None: ...

    async def print_all_results_from_db(
        self, result: List[PokemonTypes]
    ) -> None: ...
    async def query_for_count(self, ) -> List[PokemonTypeCounter]: ...
    async def save_results_json(self) -> None: ...
    async def exit(self) -> None: ...
