from typing import List
from abc import ABC

from poke_challenge.schema import PokemonTypes


class APIHandlerABC(ABC):
    def get_data_from_api(self) -> List[PokemonTypes]: ...


class JsonFileHandlerABC(ABC):
    def __init__(self, ): ...
    def dict_to_json(self, result: dict): ...
    def save_to_file(self, data: dict): ...


class DatabaseHandlerABC(ABC):
    def __init__(self): ...
    async def query_counter(self) -> int: ...
    async def store_result(self, result: List[PokemonTypes]) -> None: ...
    async def start_database(self) -> None: ...


class ControllerABC(ABC):
    database_handler: DatabaseHandlerABC
    josn_handler: JsonFileHandlerABC
    api_handler: APIHandlerABC

    async def store_all_results(self, result: List[PokemonTypes]) -> None: ...

    async def print_all_results_from_db(
        self, result: List[PokemonTypes]
    ) -> None: ...
    async def query_for_count(self, ) -> dict: ...
